import type { Article } from "@/types/content";

const cover = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;

export const staticArticles: Article[] = [
  {
    slug: "comment-choisir-agence-marketing-digital",
    title: "Comment choisir une agence marketing digital ?",
    excerpt: "Les questions utiles avant de signer : preuves, méthode, contrat, et ce qu'une agence sérieuse refuse de promettre.",
    cover: cover("photo-1557804506-669a67965ba0"),
    coverAlt: "Réunion de travail dans un studio",
    category: "Guides",
    tags: ["Agence", "PME", "Guide"],
    author: "Équipe LYNE",
    publishedAt: "2026-03-12",
    focusKeyword: "agence marketing digital",
    seoTitle: "Comment choisir une agence marketing digital",
    seoDescription: "Critères concrets pour choisir une agence marketing digital : preuves, méthode, reporting et limites d'un engagement.",
    faq: [
      { q: "Faut-il une agence dans ma ville ?", a: "La proximité peut aider pour les ateliers en présentiel. Le critère décisif reste la clarté du travail, le processus et la communication — pas l'adresse seule." },
      { q: "Quel budget prévoir ?", a: "Cela dépend du levier. Un cadrage honnête dit ce qui est possible avec votre enveloppe avant de produire." },
    ],
    blocks: [
      { type: "p", text: "Choisir une agence marketing digital n'est pas une question de plaquette. C'est le choix de quelqu'un qui va parler en votre nom, dépenser une partie de votre budget, et toucher à votre site. Le bon réflexe est de regarder la méthode, pas le vocabulaire." },
      { type: "h2", text: "Demander des preuves que l'on peut vérifier" },
      { type: "p", text: "Un portfolio sert s'il montre le problème, le travail, et un résultat. Un logo mural de marques célèbres ne dit rien. Demandez deux cas proches de votre situation : même taille d'entreprise, même type d'offre, même contrainte sectorielle. Une agence qui a accompagné une clinique, une école ou un hôtel boutique devrait pouvoir raconter ce qui a été livré." },
      { type: "ul", items: ["Un avant / après lisible", "Le rôle exact de l'agence", "Ce qui n'a pas marché, dit simplement"] },
      { type: "h2", text: "Comprendre ce qui est inclus" },
      { type: "p", text: "Création de site, SEO, Google Ads et réseaux sociaux ne sont pas le même métier. Une équipe peut les réunir, à condition de dire qui fait quoi. Méfiez-vous d'une offre qui promet « tout le digital » sans nommer les livrables du mois." },
      { type: "h2", text: "Lire le reporting avant de signer" },
      { type: "p", text: "Demandez un exemple de compte rendu. S'il ne contient que des likes et des impressions, vous ne saurez pas si le travail amène des demandes. Les indicateurs utiles sont les vôtres : appels, formulaires, rendez-vous, ventes." },
      { type: "h2", text: "Ce qu'une agence sérieuse ne promet pas" },
      { type: "p", text: "Personne ne peut garantir la première place Google ni un retour chiffré avant d'avoir vu votre offre, votre marge et votre site. Une équipe honnête le dit au premier échange. C'est souvent le meilleur critère, que l'agence soit à deux rues ou à l'autre bout du monde." },
      { type: "quote", text: "Le bon partenaire explique ce qu'il ne fera pas." },
      { type: "p", text: "Si vous comparez des agences, posez les mêmes questions à chacune et gardez les réponses écrites. Le <a href=\"/contact\">premier échange</a> avec LYNE sert à cela : voir si le sujet est le nôtre, et vous le dire si ce n'est pas le cas." },
    ],
  },
  {
    slug: "prix-creation-site-web",
    title: "Combien coûte la création d'un site web ?",
    excerpt: "Ce qui fait varier un budget : pages, contenu, paiement, langues, et la maintenance que l'on oublie souvent.",
    cover: cover("photo-1498050108023-c5249f4df085"),
    coverAlt: "Écran de travail sur un bureau",
    category: "Sites web",
    tags: ["Site web", "Budget", "PME"],
    author: "Équipe LYNE",
    publishedAt: "2026-04-02",
    focusKeyword: "prix création site web",
    seoTitle: "Prix création site web : fourchettes et postes de budget",
    seoDescription: "Comprendre le coût d'un site web : vitrine, e-commerce, contenu, langues et maintenance — repères en EUR et USD.",
    faq: [
      { q: "Un site à bas prix est-il une erreur ?", a: "Pas s'il correspond à un besoin simple et si vous savez ce qui n'est pas inclus. C'est un problème quand il empêche ensuite le référencement ou la vente." },
      { q: "Le prix inclut-il les textes ?", a: "Pas toujours. Des textes bâclés coûtent plus cher ensuite, parce que le site ne convertit pas." },
    ],
    blocks: [
      { type: "p", text: "Il n'existe pas de prix unique pour un site web. Deux devis à 3 000 € (ou environ 3 200 USD) peuvent couvrir des choses opposées : l'un un thème rempli de texte générique, l'autre un site court, écrit, et techniquement sain. La question utile est : que doit faire le site dans les douze prochains mois ?" },
      { type: "h2", text: "Ordres de grandeur utiles" },
      { type: "p", text: "Une vitrine professionnelle bien cadrée se situe souvent entre 2 500 et 8 000 € selon les pages, la rédaction et les langues. Une boutique en ligne démarre plus haut, typiquement 5 000 à 15 000 €, parce que catalogue, paiement et logistique ajoutent du travail. Une plateforme sur mesure se chiffre au cas par cas — comme un produit, pas comme une plaquette." },
      { type: "h2", text: "Les postes qui font vraiment varier le budget" },
      { type: "ul", items: ["Le nombre de pages et la complexité du parcours", "La rédaction, souvent sous-estimée", "Les langues : une ou plusieurs versions", "Le paiement en ligne et la logistique, pour une boutique", "La formation et la maintenance après la mise en ligne"] },
      { type: "h2", text: "Vitrine, catalogue, plateforme" },
      { type: "p", text: "Un site vitrine bien cadré présente l'offre, des preuves et un moyen de contact. Il coûte moins qu'une boutique, et il suffit à beaucoup de PME. Une boutique ajoute le catalogue, les stocks, les frais de livraison et les échecs de paiement. Une plateforme métier — espace client, réservation, tableau de bord — se chiffre comme un produit, pas comme une plaquette." },
      { type: "h2", text: "Ce qu'il faut prévoir en plus du devis de création" },
      { type: "p", text: "Nom de domaine, hébergement, emails, et un peu de temps chaque trimestre pour corriger ce que les visiteurs ne comprennent pas. Un site abandonné après la livraison vieillit vite, surtout sur mobile." },
      { type: "h2", text: "Comment lire un devis" },
      { type: "p", text: "Demandez la liste des pages, qui écrit, qui fournit les photos, ce qui se passe après la mise en ligne, et à qui appartient le code. Si vous hésitez entre une vitrine et une boutique, le guide <a href=\"/blog/site-vitrine-ou-ecommerce\">site vitrine ou e-commerce</a> pose la question du côté de la vente, pas du côté de la mode." },
    ],
  },
  {
    slug: "pourquoi-le-seo-est-important",
    title: "Pourquoi le SEO est important pour une entreprise ?",
    excerpt: "Google est souvent le premier commercial. Encore faut-il qu'il puisse montrer une page qui répond.",
    cover: cover("photo-1432888498266-38ffec3eaf0a"),
    coverAlt: "Analyse de trafic sur un écran",
    category: "SEO",
    tags: ["SEO", "Google", "PME"],
    author: "Équipe LYNE",
    publishedAt: "2026-05-18",
    focusKeyword: "SEO entreprise",
    seoTitle: "Pourquoi le SEO compte pour une entreprise",
    seoDescription: "Le référencement naturel aide les entreprises à être trouvées au moment où un client cherche déjà — partout dans le monde.",
    faq: [
      { q: "Le SEO remplace-t-il la publicité ?", a: "Non. La publicité agit vite, le SEO construit une présence qui reste. Les deux se complètent quand le site est clair." },
    ],
    blocks: [
      { type: "p", text: "Quand quelqu'un cherche un avocat, une école, un hôtel ou un grossiste, il commence souvent par Google. Si votre entreprise n'a pas de page qui répond, la demande va ailleurs. C'est cela, l'enjeu du SEO : être présent au moment de la recherche, sans payer chaque clic." },
      { type: "h2", text: "Chaque intention de recherche mérite une page" },
      { type: "p", text: "« Agence SEO », « dentiste près de chez moi » ou « logiciel de facturation B2B » n'attendent pas le même texte. Une page utile nomme le service, le contexte de l'acheteur, et la preuve. Répéter le mot-clé dans chaque phrase n'aide ni le lecteur ni, durablement, Google." },
      { type: "h2", text: "La technique compte autant que les articles" },
      { type: "p", text: "Un site lent, mal affiché sur mobile, ou dont les pages utiles ne sont pas indexées, limite tout le reste. Avant de publier vingt articles, il faut savoir quelles pages Google voit déjà. Search Console est le point de départ, pas un outil réservé aux grandes marques." },
      { type: "h2", text: "Le délai est le prix de la durée" },
      { type: "p", text: "Un article bien construit peut mettre plusieurs mois à trouver sa place. C'est moins spectaculaire qu'une campagne, et c'est aussi pourquoi le trafic organique reste quand le budget publicitaire s'arrête. Les entreprises qui tiennent un an de publication régulière prennent une avance difficile à rattraper par un concurrent pressé." },
      { type: "p", text: "Pour le détail d'une démarche, lisez le <a href=\"/blog/agence-seo-guide\">guide agence SEO</a> ou la page <a href=\"/services/seo\">référencement</a>." },
    ],
  },
  {
    slug: "agence-seo-guide",
    title: "Agence SEO : guide complet",
    excerpt: "Ce qu'une mission de référencement devrait contenir, du premier audit au compte rendu mensuel.",
    cover: cover("photo-1454165804606-c3d57bc86b40"),
    coverAlt: "Notes et ordinateur sur une table",
    category: "SEO",
    tags: ["SEO", "Guide", "Agence"],
    author: "Équipe LYNE",
    publishedAt: "2026-06-09",
    focusKeyword: "agence SEO",
    seoTitle: "Agence SEO : guide pour bien démarrer",
    seoDescription: "Audit, contenus, SEO local ou international et reporting : ce qu'il est raisonnable d'attendre d'une agence SEO.",
    faq: [
      { q: "Faut-il un blog ?", a: "Seulement si vous avez des questions réelles à traiter. Un blog vide de sujets utiles n'est pas une stratégie." },
    ],
    blocks: [
      { type: "p", text: "Une agence SEO devrait commencer par votre marché et vos clients, pas par un logiciel. Les recherches ne sont pas les mêmes pour une marque locale, une boutique en ligne ou un éditeur SaaS qui vise plusieurs pays. Ce guide décrit une mission saine, que vous travailliez avec nous ou avec une autre équipe." },
      { type: "h2", text: "1. L'audit, avant les promesses" },
      { type: "p", text: "L'audit regarde l'indexation, la vitesse, les pages qui se font concurrence, et les recherches où vous êtes déjà proche. Il se termine par une liste courte de priorités, pas par cinquante captures d'écran." },
      { type: "h2", text: "2. La technique et la structure" },
      { type: "p", text: "Titres, balises, maillage, données structurées, version mobile. Ce travail est invisible et il conditionne le reste. Une refonte de site sans reprise SEO est une cause classique de chute de trafic." },
      { type: "h2", text: "3. Les pages qui méritent d'exister" },
      { type: "p", text: "Mieux vaut cinq pages précises — un service, un segment, une question — que trente articles génériques. Chaque page doit pouvoir être envoyée à un client sans honte." },
      { type: "h2", text: "4. Le compte rendu" },
      { type: "p", text: "Chaque mois : ce qui a été publié ou corrigé, les pages qui gagnent des visites, les demandes si vous les mesurez, et ce qui est prévu ensuite. Un score décoratif ne remplace pas cette lecture." },
      { type: "quote", text: "Le référencement se juge sur des pages et des demandes, pas sur un pourcentage magique." },
    ],
  },
  {
    slug: "attirer-clients-digital",
    title: "Comment attirer plus de clients grâce au digital ?",
    excerpt: "Quatre leviers suffisent souvent : une offre claire, un site qui convertit, une présence recherchée, une publicité tenue.",
    cover: cover("photo-1556761175-5973dc0f32e7"),
    coverAlt: "Échange entre deux personnes dans un bureau",
    category: "Stratégie",
    tags: ["Acquisition", "PME", "Google"],
    author: "Équipe LYNE",
    publishedAt: "2026-07-01",
    focusKeyword: "attirer des clients digital",
    seoTitle: "Attirer plus de clients grâce au digital",
    seoDescription: "Offre, site, SEO et publicité : une façon simple d'attirer des clients sans empiler les canaux.",
    faq: [
      { q: "Par où commencer si le budget est limité ?", a: "Par la clarté de l'offre et une page qui reçoit les demandes. Ensuite seulement, le canal qui touche déjà vos clients." },
    ],
    blocks: [
      { type: "p", text: "Attirer plus de clients ne commence pas par un nouveau réseau social. Cela commence par une offre que l'on peut expliquer, et un endroit où la personne peut répondre. Le digital accélère ce mouvement. Il ne le remplace pas." },
      { type: "h2", text: "Rendre l'offre évidente" },
      { type: "p", text: "Si un proche ne peut pas répéter ce que vous vendez et à qui, le site ne le pourra pas non plus. Une phrase claire vaut mieux qu'une page d'accueil pleine de mots comme innovation, excellence et solutions." },
      { type: "h2", text: "Choisir un canal principal" },
      { type: "ul", items: ["Vos clients cherchent déjà : SEO et Google Ads", "Ils découvrent en regardant : Meta et contenus", "Ils comparent longtemps : site, preuves, relance"] },
      { type: "p", text: "Tenir un canal correctement bat toujours la présence symbolique sur cinq plateformes. Messagerie, email ou formulaire : le site doit mener vers le contact que vos clients utilisent vraiment, sans friction." },
      { type: "h2", text: "Mesurer les demandes, pas l'agitation" },
      { type: "p", text: "Comptez les messages qualifiés, les appels, les rendez-vous. Si ces chiffres n'existent pas, la première mission digitale est de les créer. Le reste est une conversation plus honnête." },
    ],
  },
  {
    slug: "site-vitrine-ou-ecommerce",
    title: "Site vitrine ou site e-commerce : lequel choisir ?",
    excerpt: "Le bon choix dépend de la façon dont vos clients achètent, pas de ce qui se fait dans votre secteur en apparence.",
    cover: cover("photo-1472851294608-062f824d29cc"),
    coverAlt: "Rayonnage d'une boutique",
    category: "Sites web",
    tags: ["E-commerce", "Site web", "Budget"],
    author: "Équipe LYNE",
    publishedAt: "2026-08-14",
    focusKeyword: "site vitrine ou e-commerce",
    seoTitle: "Site vitrine ou e-commerce : comment choisir",
    seoDescription: "Comparer un site vitrine et une boutique en ligne selon la vente, la logistique et le budget.",
    faq: [
      { q: "Peut-on commencer par une vitrine puis vendre ?", a: "Oui, si l'architecture le prévoit. Ajouter un paiement sur un site non pensé pour cela crée souvent une deuxième refonte." },
    ],
    blocks: [
      { type: "p", text: "Un site vitrine présente et qualifie. Un site e-commerce encaisse. Le mauvais choix coûte du temps : une boutique lancée sans logistique, ou une vitrine alors que vos clients veulent payer le soir sur leur téléphone." },
      { type: "h2", text: "Choisissez une vitrine si…" },
      { type: "ul", items: ["La vente se conclut en rendez-vous, sur devis ou en magasin", "Chaque projet est différent", "Vous avez besoin de confiance plus que d'un panier"] },
      { type: "h2", text: "Choisissez une boutique si…" },
      { type: "ul", items: ["Le prix est public", "Vous pouvez livrer ou retirer de façon fiable", "Le même produit se vend à beaucoup de personnes"] },
      { type: "h2", text: "Paiement et confiance" },
      { type: "p", text: "Carte bancaire, PayPal, Stripe ou facturation B2B : le moyen doit correspondre à vos clients réels et à votre marché. Une boutique jolie avec un paiement que personne n'utilise est un catalogue frustrant. Prévoyez aussi les retours et le service après-vente avant d'acheter du trafic." },
      { type: "p", text: "Si vous hésitez, décrivez une vente typique — de la première question au paiement — et le format devient souvent évident. Nous pouvons le faire avec vous lors d'un <a href=\"/contact\">échange</a>." },
    ],
  },
];

export const articleSlugs = staticArticles.map((article) => article.slug);
