import type { Locale } from "@/i18n/routing";
import type { Service } from "@/types/content";

const img = {
  web: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1600&q=80",
  seo: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=1600&q=80",
  marketing: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1600&q=80",
  ads: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1600&q=80",
  meta: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=1600&q=80",
  social: "https://images.unsplash.com/photo-1611162616475-46b635cb6868?auto=format&fit=crop&w=1600&q=80",
  brand: "https://images.unsplash.com/photo-1634942537034-2531766767d1?auto=format&fit=crop&w=1600&q=80",
  shop: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1600&q=80",
};

type Copy = Omit<Service, "slug" | "icon" | "image" | "tools">;

const services: Array<Omit<Service, keyof Copy> & { copy: Record<Locale, Copy> }> = [
  {
    slug: "creation-site-web",
    icon: "Monitor",
    image: img.web,
    tools: ["Next.js", "React", "Tailwind", "Headless CMS"],
    copy: {
      fr: {
        name: "Création de sites web",
        summary: "Sites vitrines, corporate et plateformes conçus pour être rapides, clairs et utiles à la vente.",
        description:
          "Un site n'est pas une brochure. Nous le construisons comme un outil : message net, parcours court, base technique saine, et une administration que vous pouvez tenir sans nous appeler pour chaque virgule.",
        problem:
          "Beaucoup d'entreprises ont un site lent, illisible sur mobile, ou joli mais incapable de produire une demande. Le référencement et la publicité n'y changent rien si la page n'explique pas l'offre.",
        solution:
          "Nous concevons et développons des sites sur mesure, le plus souvent avec Next.js. Structure, design, contenu et performance sont décidés ensemble, puis mesurés après la mise en ligne.",
        benefits: [
          "Un message compréhensible en quelques secondes",
          "Un site rapide sur mobile, là où sont vos clients",
          "Une base SEO propre dès la première version",
          "Un back-office pour faire évoluer le contenu",
        ],
        process: [
          { title: "Cadrage", text: "Offre, audiences, pages indispensables, et ce que le site doit faire gagner." },
          { title: "Direction", text: "Architecture, ton, et une direction visuelle avant de produire toutes les pages." },
          { title: "Construction", text: "Intégration, contenus, formulaires, mesures, et recette sur mobile." },
          { title: "Mise en ligne", text: "Déploiement, Search Console, et un point de suivi après les premières semaines." },
        ],
        faq: [
          { q: "Travaillez-vous avec WordPress ?", a: "Oui quand c'est le bon outil. Pour un site qui doit durer et rester rapide, nous recommandons souvent Next.js." },
          { q: "Combien de temps faut-il ?", a: "Un site vitrine cadré se livre en général entre trois et six semaines. Une plateforme plus large demande un planning dédié." },
        ],
        seoTitle: "Création de site web — studio digital",
        seoDescription: "Sites vitrines, corporate et plateformes Next.js, rapides, clairs et pensés pour recevoir des demandes — en remote, partout dans le monde.",
      },
      en: {
        name: "Website design",
        summary: "Brochure sites, corporate sites and platforms built to be fast, clear and useful for sales.",
        description: "A website is not a brochure. We build it as a tool: a sharp message, a short path, a sound technical base, and an admin you can run without calling us for every comma.",
        problem: "Many companies have a slow site, a poor mobile experience, or a pretty page that never produces an enquiry. Ads and SEO cannot fix a page that does not explain the offer.",
        solution: "We design and build custom websites, most often with Next.js. Structure, design, content and performance are decided together, then reviewed after launch.",
        benefits: ["A message understood in seconds", "A fast mobile site", "A clean SEO base from version one", "A back office you can update"],
        process: [
          { title: "Frame", text: "Offer, audiences, essential pages, and what the site should earn." },
          { title: "Direction", text: "Architecture, tone, and a visual direction before every page is produced." },
          { title: "Build", text: "Integration, content, forms, measurement, and a mobile review." },
          { title: "Launch", text: "Deployment, Search Console, and a follow-up after the first weeks." },
        ],
        faq: [
          { q: "Do you use WordPress?", a: "Yes when it is the right tool. When a site must stay fast, we usually recommend Next.js." },
          { q: "How long does it take?", a: "A focused brochure site usually ships in three to six weeks. A larger platform needs its own plan." },
        ],
        seoTitle: "Website design — digital studio",
        seoDescription: "Brochure sites, corporate sites and Next.js platforms built to receive enquiries — remote-friendly, worldwide.",
      },
      ar: {
        name: "إنشاء مواقع الويب",
        summary: "مواقع تعريفية ومؤسسية ومنصات سريعة وواضحة ومفيدة للبيع.",
        description: "الموقع ليس مطوية. نبنيه كأداة: رسالة واضحة، مسار قصير، أساس تقني سليم، ولوحة إدارة يمكنكم تسييرها.",
        problem: "كثير من الشركات لديها موقع بطيء أو ضعيف على الهاتف، أو جميل لكنه لا يولّد طلبات.",
        solution: "نصمم ونطوّر مواقع حسب الطلب، غالبًا بـ Next.js. البنية والتصميم والمحتوى والأداء تُقرَّر معًا ثم تُراجع بعد الإطلاق.",
        benefits: ["رسالة تُفهم في ثوانٍ", "موقع سريع على الهاتف", "أساس SEO نظيف", "لوحة تحكم لتحديث المحتوى"],
        process: [
          { title: "تأطير", text: "العرض، الجمهور، والصفحات الضرورية." },
          { title: "اتجاه", text: "البنية والنبرة والاتجاه البصري قبل إنتاج كل الصفحات." },
          { title: "بناء", text: "التكامل والمحتوى والنماذج والقياس." },
          { title: "إطلاق", text: "النشر وSearch Console ومتابعة الأسابيع الأولى." },
        ],
        faq: [
          { q: "هل تعملون بـ WordPress؟", a: "نعم حين يكون الأداة المناسبة. للسرعة على المدى الطويل ننصح غالبًا بـ Next.js." },
          { q: "كم تستغرق المدة؟", a: "موقع تعريفي مؤطَّر يُسلَّم عادة بين ثلاثة وستة أسابيع." },
        ],
        seoTitle: "إنشاء مواقع ويب — استوديو رقمي",
        seoDescription: "مواقع تعريفية ومنصات Next.js سريعة ومصممة لاستقبال الطلبات — عن بُعد، لعلامات في العالم.",
      },
    },
  },
  {
    slug: "seo",
    icon: "Search",
    image: img.seo,
    tools: ["Search Console", "Semrush", "Ahrefs", "Schema.org"],
    copy: {
      fr: {
        name: "SEO",
        summary: "Visibilité durable sur Google : technique, contenus et pages alignées sur vos marchés.",
        description: "Le référencement utile n'est pas une liste de mots-clés. C'est un site compréhensible, des pages qui répondent à de vraies recherches, et un suivi mensuel honnête.",
        problem: "Être absent de Google quand un client cherche votre métier ou votre produit, c'est laisser la demande à ceux qui ont publié avant vous.",
        solution: "Nous auditons la technique, la structure et les contenus, puis nous produisons les pages qui méritent de remonter. Nous ne promettons pas la première place. Nous documentons le travail et les mouvements.",
        benefits: ["Des pages alignées sur des recherches réelles", "Une base technique que Google peut lire", "Un plan éditorial ciblé, sans bourrage", "Un reporting lisible chaque mois"],
        process: [
          { title: "Audit", text: "Indexation, vitesse, pages utiles, et écart avec les recherches de vos clients." },
          { title: "Plan", text: "Priorités techniques et sujets à publier, classés par intention." },
          { title: "Production", text: "Corrections, pages services, articles et maillage interne." },
          { title: "Lecture", text: "Positions, pages qui reçoivent des visites, et demandes associées." },
        ],
        faq: [
          { q: "En combien de temps voit-on un effet ?", a: "Les corrections techniques peuvent aider vite. Les contenus mettent souvent trois à six mois à porter." },
          { q: "Garantissez-vous la première position ?", a: "Non. Personne de sérieux ne le peut. Nous garantissons un travail traçable." },
        ],
        seoTitle: "Agence SEO — référencement durable",
        seoDescription: "Référencement technique, contenus et visibilité internationale pour les marques qui veulent être trouvées sur Google.",
      },
      en: {
        name: "SEO",
        summary: "Durable visibility on Google: technical work, content and pages aligned with your markets.",
        description: "Useful SEO is not a keyword list. It is a site Google can read, pages that answer real searches, and an honest monthly review.",
        problem: "If you are absent when a client searches your trade or product, that demand goes to whoever published first.",
        solution: "We audit technique, structure and content, then produce the pages that deserve to rise. We do not promise the first position. We document the work and the movement.",
        benefits: ["Pages aligned with real searches", "A technical base Google can read", "A focused editorial plan", "A readable monthly report"],
        process: [
          { title: "Audit", text: "Indexing, speed, useful pages, and the gap with what clients search." },
          { title: "Plan", text: "Technical priorities and topics, ranked by intent." },
          { title: "Production", text: "Fixes, service pages, articles and internal links." },
          { title: "Reading", text: "Rankings, pages that receive visits, and related enquiries." },
        ],
        faq: [
          { q: "How fast does it work?", a: "Technical fixes can help quickly. Content often takes three to six months." },
          { q: "Do you guarantee the first position?", a: "No. Nobody serious can. We guarantee traceable work." },
        ],
        seoTitle: "SEO agency — durable search visibility",
        seoDescription: "Technical SEO, content and international visibility for brands that want to be found on Google.",
      },
      ar: {
        name: "تحسين محركات البحث",
        summary: "ظهور دائم على Google: الجانب التقني والمحتوى وصفحات مطابقة لأسواقكم.",
        description: "السيو المفيد ليس لائحة كلمات. هو موقع يفهمه Google وصفحات تجيب عن بحوث حقيقية ومتابعة شهرية صادقة.",
        problem: "إذا غبتم حين يبحث زبون عن مهنتكم أو منتجكم، يذهب الطلب إلى من نشر قبلكم.",
        solution: "ندقق التقنية والبنية والمحتوى، ثم ننتج الصفحات التي تستحق الصعود. لا نعد بالمرتبة الأولى. نوثّق العمل والحركة.",
        benefits: ["صفحات مطابقة لبحوث حقيقية", "أساس تقني واضح", "خطة تحرير مركّزة", "تقرير شهري مقروء"],
        process: [
          { title: "تدقيق", text: "الفهرسة والسرعة والصفحات المفيدة." },
          { title: "خطة", text: "أولويات تقنية ومواضيع حسب النية." },
          { title: "إنتاج", text: "تصحيحات وصفحات خدمات ومقالات وروابط داخلية." },
          { title: "قراءة", text: "الترتيب والزيارات والطلبات المرتبطة." },
        ],
        faq: [
          { q: "متى تظهر النتيجة؟", a: "التصحيحات التقنية قد تساعد سريعًا. المحتوى يحتاج غالبًا ثلاثة إلى ستة أشهر." },
          { q: "هل تضمنون المرتبة الأولى؟", a: "لا. لا أحد جاد يضمن ذلك. نضمن عملًا يمكن تتبعه." },
        ],
        seoTitle: "وكالة SEO — ظهور مستدام",
        seoDescription: "سيو تقني ومحتوى وظهور دولي للعلامات التي تريد أن تُوجد على Google.",
      },
    },
  },
];

function rest(): Array<(typeof services)[number]> {
  const pack = (
    slug: string,
    icon: string,
    image: string,
    tools: string[],
    fr: Copy,
    en: Copy,
    ar: Copy,
  ): (typeof services)[number] => ({ slug, icon, image, tools, copy: { fr, en, ar } });

  return [
    pack(
      "marketing-digital",
      "LineChart",
      img.marketing,
      ["Analytics", "Looker Studio", "CRM"],
      {
        name: "Marketing digital",
        summary: "Une stratégie d'acquisition simple : qui viser, où parler, et comment reconnaître une demande utile.",
        description: "Nous relions le site, le référencement, la publicité et les contenus à un objectif commercial. Pas de plan de 80 pages : un cap, des priorités, et un rythme de revue.",
        problem: "Les actions s'empilent — un peu de pubs, un peu de posts, un site à part — sans que personne ne sache ce qui amène réellement un client.",
        solution: "Nous posons le parcours, choisissons peu de canaux, et définissons les indicateurs qui comptent pour votre activité, pas pour un tableau décoratif.",
        benefits: ["Un cap partagé", "Moins de dispersion", "Des budgets lisibles", "Des décisions mensuelles"],
        process: [
          { title: "Lecture", text: "Offre, marge, saisonnalité, et ce que vos clients font déjà en ligne." },
          { title: "Choix", text: "Deux ou trois leviers, pas dix. Chacun a un rôle." },
          { title: "Mise en œuvre", text: "Avec nos équipes ou les vôtres, selon ce que vous voulez garder en interne." },
          { title: "Revue", text: "Ce qui a produit des demandes, ce qui doit s'arrêter." },
        ],
        faq: [
          { q: "Est-ce un accompagnement au mois ?", a: "Souvent oui, après un cadrage. Certaines missions restent ponctuelles." },
          { q: "Travaillez-vous à distance ?", a: "Oui. Nous collaborons en remote avec des équipes en Europe, au Moyen-Orient, en Amérique du Nord et ailleurs, avec des points de sync réguliers." },
        ],
        seoTitle: "Agence marketing digital",
        seoDescription: "Stratégie d'acquisition pour marques internationales : site, SEO, publicité et contenus reliés à un objectif commercial.",
      },
      {
        name: "Digital marketing",
        summary: "A simple acquisition strategy: who to reach, where to speak, and how to recognise a useful enquiry.",
        description: "We connect the website, SEO, advertising and content to a commercial goal. No 80-page plan: a direction, priorities, and a review rhythm.",
        problem: "Actions pile up — some ads, some posts, a separate website — and nobody knows what actually brings a client.",
        solution: "We map the path, choose few channels, and define the indicators that matter for your business.",
        benefits: ["A shared direction", "Less scatter", "Readable budgets", "Monthly decisions"],
        process: [
          { title: "Read", text: "Offer, margin, season, and what your clients already do online." },
          { title: "Choose", text: "Two or three levers, not ten. Each has a role." },
          { title: "Run", text: "With our team or yours, depending on what you want to keep inside." },
          { title: "Review", text: "What produced enquiries, and what should stop." },
        ],
        faq: [
          { q: "Is this a monthly retainer?", a: "Often, after a framing phase. Some missions stay one-off." },
          { q: "Do you work remotely?", a: "Yes. We collaborate remotely with teams across Europe, the Middle East, North America and beyond, with regular sync points." },
        ],
        seoTitle: "Digital marketing agency",
        seoDescription: "Acquisition strategy for international brands: website, SEO, ads and content tied to a commercial goal.",
      },
      {
        name: "التسويق الرقمي",
        summary: "استراتيجية اكتساب بسيطة: من نستهدف، أين نتحدث، وكيف نعرف الطلب المفيد.",
        description: "نربط الموقع والسيو والإعلان والمحتوى بهدف تجاري. لا خطة من 80 صفحة: اتجاه وأولويات وإيقاع مراجعة.",
        problem: "تتراكم الأفعال — إعلانات ومنشورات وموقع منفصل — دون أن يعرف أحد ما يجلب الزبون فعلًا.",
        solution: "نرسم المسار، نختار قنوات قليلة، ونحدد المؤشرات التي تهم نشاطكم.",
        benefits: ["اتجاه مشترك", "تشتت أقل", "ميزانيات مقروءة", "قرارات شهرية"],
        process: [
          { title: "قراءة", text: "العرض والهامش والموسم وسلوك الزبائن." },
          { title: "اختيار", text: "رافعتان أو ثلاث، لا عشر." },
          { title: "تنفيذ", text: "مع فريقنا أو فريقكم." },
          { title: "مراجعة", text: "ما أنتج طلبات وما يجب أن يتوقف." },
        ],
        faq: [
          { q: "هل المرافقة شهرية؟", a: "غالبًا بعد مرحلة تأطير. بعض المهام تبقى محددة." },
          { q: "هل تعملون عن بُعد؟", a: "نعم. نتعاون عن بُعد مع فرق في أوروبا والشرق الأوسط وأمريكا الشمالية وغيرها، مع نقاط متابعة منتظمة." },
        ],
        seoTitle: "وكالة تسويق رقمي",
        seoDescription: "استراتيجية اكتساب للعلامات الدولية: موقع وSEO وإعلانات ومحتوى مربوطة بهدف تجاري.",
      },
    ),
    pack(
      "google-ads",
      "MousePointerClick",
      img.ads,
      ["Google Ads", "GA4", "Search Console"],
      {
        name: "Google Ads",
        summary: "Campagnes Search, Display et Performance Max pilotées sur les demandes, pas sur les clics seuls.",
        description: "La publicité Google sert quand quelqu'un cherche déjà. Nous structurons les campagnes, les annonces et les pages d'arrivée pour que le budget devienne des conversations.",
        problem: "Un compte mal tenu dépense vite : mots-clés trop larges, pages lentes, et aucune distinction entre un clic curieux et une demande.",
        solution: "Nous reprenons ou lançons le compte, isolons les recherches rentables, et relions chaque campagne à une page capable de convertir.",
        benefits: ["Un budget suivi de près", "Des recherches qualifiées", "Des pages d'arrivée alignées", "Un compte que vous pouvez comprendre"],
        process: [
          { title: "Compte", text: "Historique, conversion, et ce qu'une demande vaut pour vous." },
          { title: "Structure", text: "Campagnes séparées par intention, annonces et extensions." },
          { title: "Pages", text: "Le message de l'annonce doit se retrouver sur la page." },
          { title: "Optimisation", text: "Termes de recherche, enchères, et créations qui fatiguent." },
        ],
        faq: [
          { q: "Faut-il un gros budget ?", a: "Non. Mieux vaut un budget modeste bien tenu qu'un gros compte dispersé. Nous le disons avant de lancer." },
          { q: "Le budget pub est-il inclus ?", a: "Non. Il est payé directement à Google. Nos honoraires couvrent le pilotage." },
        ],
        seoTitle: "Google Ads — campagnes Search",
        seoDescription: "Pilotage de campagnes Google Ads pour générer des demandes qualifiées, avec des pages d'arrivée cohérentes.",
      },
      {
        name: "Google Ads",
        summary: "Search, Display and Performance Max campaigns judged on enquiries, not on clicks alone.",
        description: "Google ads work when someone is already searching. We structure campaigns, ads and landing pages so the budget becomes conversations.",
        problem: "A loose account spends fast: broad keywords, slow pages, and no line between a curious click and an enquiry.",
        solution: "We take over or launch the account, isolate profitable searches, and tie each campaign to a page that can convert.",
        benefits: ["A closely watched budget", "Qualified searches", "Aligned landing pages", "An account you can understand"],
        process: [
          { title: "Account", text: "History, conversion, and what an enquiry is worth to you." },
          { title: "Structure", text: "Campaigns split by intent, ads and extensions." },
          { title: "Pages", text: "The ad's promise has to be on the page." },
          { title: "Optimise", text: "Search terms, bids, and creatives that tire." },
        ],
        faq: [
          { q: "Do we need a large budget?", a: "No. A modest, well-run budget beats a scattered large account." },
          { q: "Is the media budget included?", a: "No. You pay Google directly. Our fee covers the steering." },
        ],
        seoTitle: "Google Ads — Search campaigns",
        seoDescription: "Google Ads management for qualified enquiries worldwide, with landing pages that match the campaign.",
      },
      {
        name: "إعلانات Google",
        summary: "حملات Search وDisplay وPerformance Max تُقاس بالطلبات لا بالنقرات وحدها.",
        description: "إعلان Google ينفع حين يبحث الشخص أصلًا. نبني الحملات والإعلانات وصفحات الوصول ليصبح الميزانية محادثات.",
        problem: "حساب غير مضبوط يصرف بسرعة: كلمات عريضة وصفحات بطيئة وبلا تمييز بين نقرة وطلب.",
        solution: "نتسلم الحساب أو نطلقه، نعزل البحوث المربحة، ونربط كل حملة بصفحة قادرة على التحويل.",
        benefits: ["ميزانية مراقبة", "بحوث مؤهلة", "صفحات وصول متسقة", "حساب يمكن فهمه"],
        process: [
          { title: "الحساب", text: "التاريخ والتحويل وقيمة الطلب." },
          { title: "البنية", text: "حملات حسب النية." },
          { title: "الصفحات", text: "وعد الإعلان يجب أن يوجد في الصفحة." },
          { title: "التحسين", text: "عبارات البحث والمزايدات." },
        ],
        faq: [
          { q: "هل نحتاج ميزانية كبيرة؟", a: "لا. ميزانية متواضعة مضبوطة أفضل من حساب كبير مشتت." },
          { q: "هل ميزانية الإعلان داخلة؟", a: "لا. تُدفع لـ Google مباشرة. أتعابنا تغطي القيادة." },
        ],
        seoTitle: "إعلانات Google — حملات Search",
        seoDescription: "إدارة حملات Google Ads لطلبات مؤهلة مع صفحات وصول متسقة.",
      },
    ),
    pack(
      "meta-ads",
      "Share2",
      img.meta,
      ["Meta Ads", "Pixel", "Instagram"],
      {
        name: "Meta Ads",
        summary: "Facebook et Instagram pour présenter une offre à des gens qui ne vous cherchent pas encore.",
        description: "Meta est fort quand l'offre se montre : un lieu, un produit, une promotion, une prise de rendez-vous. Nous créons les campagnes et les visuels qui méritent l'interruption.",
        problem: "Booster des posts au hasard fatigue l'audience et apprend peu. Sans pixel, sans offre, sans page de suite, le coût par message grimpe.",
        solution: "Nous définissons l'audience, l'offre et la création, puis nous lisons les coûts par résultat utile : message, appel, achat, pas seulement la portée.",
        benefits: ["Une offre explicite", "Des créations testées", "Un suivi des conversions", "Un rythme de publication publicitaire tenu"],
        process: [
          { title: "Offre", text: "Ce que la personne doit faire après avoir vu l'annonce." },
          { title: "Création", text: "Quelques angles, pas cinquante visuels décoratifs." },
          { title: "Diffusion", text: "Audiences, placements, et budget d'apprentissage." },
          { title: "Lecture", text: "Coût par message ou par vente, puis on coupe ou on amplifie." },
        ],
        faq: [
          { q: "Faut-il déjà une communauté ?", a: "Non. Une campagne peut toucher des gens qui ne vous suivent pas. Une page claire reste nécessaire." },
          { q: "Produisez-vous les visuels ?", a: "Oui, avec la direction de création du studio, ou à partir de vos photos si elles sont bonnes." },
        ],
        seoTitle: "Meta Ads — Facebook et Instagram",
        seoDescription: "Campagnes Facebook et Instagram Ads pour marques internationales, pilotées sur les messages, appels et ventes.",
      },
      {
        name: "Meta Ads",
        summary: "Facebook and Instagram for an offer shown to people who are not searching for you yet.",
        description: "Meta is strong when the offer can be shown: a place, a product, a promotion, a booking. We build the campaigns and visuals that deserve the interruption.",
        problem: "Boosting random posts tires the audience and teaches little. Without a pixel, an offer and a next page, the cost per message climbs.",
        solution: "We define audience, offer and creative, then read the cost per useful result: message, call, purchase — not reach alone.",
        benefits: ["An explicit offer", "Tested creatives", "Conversion tracking", "A steady ad rhythm"],
        process: [
          { title: "Offer", text: "What the person should do after the ad." },
          { title: "Creative", text: "A few angles, not fifty decorative visuals." },
          { title: "Delivery", text: "Audiences, placements, and a learning budget." },
          { title: "Reading", text: "Cost per message or sale, then cut or scale." },
        ],
        faq: [
          { q: "Do we need a community first?", a: "No. A campaign can reach people who do not follow you. A clear page is still required." },
          { q: "Do you make the visuals?", a: "Yes, with the studio's art direction, or from your photos when they are good." },
        ],
        seoTitle: "Meta Ads — Facebook and Instagram",
        seoDescription: "Facebook and Instagram campaigns for international brands, judged on messages, calls and sales.",
      },
      {
        name: "إعلانات Meta",
        summary: "فيسبوك وإنستغرام لعرض خدمة على أناس لا يبحثون عنكم بعد.",
        description: "Meta قوي حين تُعرض الخدمة: مكان، منتج، عرض، حجز. نبني الحملات والمرئيات التي تستحق المقاطعة.",
        problem: "تعزيز منشورات عشوائية يرهق الجمهور ولا يعلّم الكثير.",
        solution: "نحدد الجمهور والعرض والإبداع، ثم نقرأ التكلفة لكل نتيجة مفيدة: رسالة، اتصال، شراء.",
        benefits: ["عرض صريح", "إبداعات مختبَرة", "تتبع التحويلات", "إيقاع إعلاني ثابت"],
        process: [
          { title: "العرض", text: "ماذا يفعل الشخص بعد الإعلان." },
          { title: "الإبداع", text: "زوايا قليلة لا عشرات الصور." },
          { title: "البث", text: "الجمهور والمواضع وميزانية التعلم." },
          { title: "القراءة", text: "التكلفة لكل رسالة أو بيع." },
        ],
        faq: [
          { q: "هل نحتاج جمهورًا قبلًا؟", a: "لا. الحملة تصل إلى من لا يتابعكم. الصفحة الواضحة تبقى ضرورية." },
          { q: "هل تنتجون الصور؟", a: "نعم، مع إدارة فنية، أو من صوركم إن كانت جيدة." },
        ],
        seoTitle: "إعلانات Meta — فيسبوك وإنستغرام",
        seoDescription: "حملات فيسبوك وإنستغرام للعلامات الدولية، تُقاس بالرسائل والمكالمات والمبيعات.",
      },
    ),
    pack(
      "social-media",
      "Megaphone",
      img.social,
      ["Instagram", "Facebook", "LinkedIn", "TikTok"],
      {
        name: "Social media",
        summary: "Une présence tenue : ligne éditoriale, contenus, et animation sans publier pour publier.",
        description: "Nous construisons une voix reconnaissable et un rythme que votre équipe peut comprendre. Le community management sert la marque et, quand c'est pertinent, l'acquisition.",
        problem: "Publier tous les jours sans sujet fatigue tout le monde. Une page inactive, à l'inverse, rend le site moins crédible quand on vérifie qui vous êtes.",
        solution: "Une ligne, des formats répétables, une production mensuelle, et des réponses aux messages qui comptent. Nous mesurons les conversations, pas seulement les likes.",
        benefits: ["Une voix stable", "Moins de stress de publication", "Des contenus réutilisables en pub", "Une présence qui rassure avant l'achat"],
        process: [
          { title: "Voix", text: "Ce que vous dites, ce que vous ne dites pas, et à qui." },
          { title: "Grille", text: "Sujets et formats pour le mois, validés avant la production." },
          { title: "Production", text: "Textes, visuels, et adaptations par réseau." },
          { title: "Animation", text: "Publication, réponses, et lecture de ce qui a vraiment engagé." },
        ],
        faq: [
          { q: "Sur quels réseaux ?", a: "Là où sont vos clients. Souvent Instagram et Facebook, LinkedIn pour le B2B, TikTok si le format a un sens." },
          { q: "Pouvez-vous seulement conseiller ?", a: "Oui. Certaines équipes produisent en interne et nous gardons la direction." },
        ],
        seoTitle: "Community management et contenus",
        seoDescription: "Stratégie social media, création de contenus et animation de comptes pour marques internationales.",
      },
      {
        name: "Social media",
        summary: "A kept presence: editorial line, content, and community work without posting for the sake of it.",
        description: "We build a recognisable voice and a rhythm your team can understand. Community management serves the brand and, when it makes sense, acquisition.",
        problem: "Posting every day without a subject tires everyone. A silent page, on the other hand, makes the website less credible.",
        solution: "A line, repeatable formats, a monthly production, and replies to the messages that matter. We measure conversations, not only likes.",
        benefits: ["A stable voice", "Less publishing stress", "Content you can reuse in ads", "A presence that reassures before purchase"],
        process: [
          { title: "Voice", text: "What you say, what you do not, and to whom." },
          { title: "Grid", text: "Subjects and formats for the month, approved before production." },
          { title: "Production", text: "Copy, visuals, and adaptations per network." },
          { title: "Care", text: "Publishing, replies, and a reading of what truly engaged." },
        ],
        faq: [
          { q: "Which networks?", a: "Where your clients are. Often Instagram and Facebook, LinkedIn for B2B, TikTok when the format fits." },
          { q: "Can you only advise?", a: "Yes. Some teams produce internally and we keep the direction." },
        ],
        seoTitle: "Social media management",
        seoDescription: "Social strategy, content and community management for international brands.",
      },
      {
        name: "التواصل الاجتماعي",
        summary: "حضور مستمر: خط تحريري ومحتوى وتسيير بلا نشر من أجل النشر.",
        description: "نبني صوتًا يُعرف وإيقاعًا يفهمه فريقكم. إدارة المجتمع تخدم العلامة، وحين يلزم، الاكتساب.",
        problem: "النشر اليومي بلا موضوع يرهق الجميع. والصفحة الصامتة تجعل الموقع أقل مصداقية.",
        solution: "خط، قوالب قابلة للتكرار، إنتاج شهري، ورد على الرسائل المهمة. نقيس المحادثات لا الإعجابات فقط.",
        benefits: ["صوت ثابت", "ضغط نشر أقل", "محتوى يُعاد في الإعلان", "حضور يطمئن قبل الشراء"],
        process: [
          { title: "الصوت", text: "ماذا تقولون ولمن." },
          { title: "الشبكة", text: "مواضيع الشهر قبل الإنتاج." },
          { title: "الإنتاج", text: "نصوص ومرئيات لكل شبكة." },
          { title: "التنشيط", text: "نشر ورد وقراءة ما تفاعل فعلًا." },
        ],
        faq: [
          { q: "على أي شبكات؟", a: "حيث يوجد زبائنكم. غالبًا إنستغرام وفيسبوك، ولينكدإن للأعمال." },
          { q: "هل يمكن الاستشارة فقط؟", a: "نعم. بعض الفرق تنتج داخليًا ونحن نُبقي الاتجاه." },
        ],
        seoTitle: "إدارة التواصل الاجتماعي",
        seoDescription: "استراتيجية محتوى وإدارة حسابات للعلامات الدولية.",
      },
    ),
    pack(
      "branding",
      "Palette",
      img.brand,
      ["Identité", "Direction artistique", "Guidelines"],
      {
        name: "Branding",
        summary: "Nom, signe, ton et système visuel pour être reconnu avant même d'être comparé.",
        description: "L'identité n'est pas un logo posé sur une carte. C'est la façon dont l'entreprise se présente sur le site, les réseaux, un devis et une devanture.",
        problem: "Un signe générique, des couleurs au hasard et un discours interchangeable rendent l'offre plus difficile à mémoriser et à défendre sur le prix.",
        solution: "Nous clarifions le positionnement, puis nous dessinons un système sobre que vos équipes peuvent appliquer. Le site et les contenus naissent de cette base, pas l'inverse.",
        benefits: ["Un positionnement dit simplement", "Un signe distinct", "Des règles utilisables", "Une continuité entre le web et le reste"],
        process: [
          { title: "Position", text: "Pour qui vous êtes le bon choix, et pourquoi." },
          { title: "Territoire", text: "Mots, images, et ce que la marque refuse." },
          { title: "Système", text: "Signe, typographie, couleurs, exemples." },
          { title: "Déploiement", text: "Site, réseaux, documents. Le minimum pour que ce soit visible." },
        ],
        faq: [
          { q: "Faites-vous seulement un logo ?", a: "Si le besoin est vraiment un signe seul, oui. La plupart du temps, le signe sans usage ne sert pas." },
          { q: "Peut-on garder notre nom ?", a: "Oui. Beaucoup de missions partent d'un nom déjà connu et clarifient le reste." },
        ],
        seoTitle: "Branding et identité visuelle",
        seoDescription: "Positionnement, logo et système visuel pour les marques qui veulent être reconnues à l'international.",
      },
      {
        name: "Branding",
        summary: "Name, mark, tone and a visual system so you are recognised before you are compared.",
        description: "Identity is not a logo on a card. It is how the company shows up on the site, social, a quote and a storefront.",
        problem: "A generic mark, random colours and interchangeable copy make the offer harder to remember and harder to defend on price.",
        solution: "We clarify the position, then draw a sober system your team can apply. The site and the content come from that base.",
        benefits: ["A position said simply", "A distinct mark", "Rules people can use", "Continuity between web and the rest"],
        process: [
          { title: "Position", text: "For whom you are the right choice, and why." },
          { title: "Territory", text: "Words, images, and what the brand refuses." },
          { title: "System", text: "Mark, type, colour, examples." },
          { title: "Rollout", text: "Site, social, documents. The minimum to make it visible." },
        ],
        faq: [
          { q: "Do you only design a logo?", a: "If the need is truly a mark alone, yes. Most of the time a mark without use does not help." },
          { q: "Can we keep our name?", a: "Yes. Many missions start from a known name and clarify the rest." },
        ],
        seoTitle: "Branding and visual identity",
        seoDescription: "Positioning, logo and visual system for brands that want to be recognised internationally.",
      },
      {
        name: "الهوية البصرية",
        summary: "اسم وعلامة ونبرة ونظام بصري لتُعرفوا قبل أن تُقارَنوا.",
        description: "الهوية ليست شعارًا على بطاقة. هي طريقة ظهور المقاولة في الموقع والشبكات والعرض والواجهة.",
        problem: "علامة عامة وألوان عشوائية وخطاب قابل للاستبدال تجعل العرض أصعب في التذكر والدفاع عن السعر.",
        solution: "نوضح التموضع ثم نرسم نظامًا رصينًا يمكن لفريقكم تطبيقه.",
        benefits: ["تموضع يُقال ببساطة", "علامة مميزة", "قواعد قابلة للاستعمال", "استمرارية بين الويب والباقي"],
        process: [
          { title: "التموضع", text: "لمن أنتم الخيار الصحيح." },
          { title: "المجال", text: "الكلمات والصور وما ترفضه العلامة." },
          { title: "النظام", text: "العلامة والخط والألوان." },
          { title: "النشر", text: "الموقع والشبكات والوثائق." },
        ],
        faq: [
          { q: "هل تصممون الشعار فقط؟", a: "إذا كانت الحاجة علامة فقط، نعم. غالبًا العلامة بلا استعمال لا تنفع." },
          { q: "هل نبقي اسمنا؟", a: "نعم. كثير من المهام تنطلق من اسم معروف." },
        ],
        seoTitle: "الهوية البصرية والعلامة",
        seoDescription: "تموضع وشعار ونظام بصري للعلامات التي تريد أن تُعرف دوليًا.",
      },
    ),
    pack(
      "ecommerce",
      "ShoppingBag",
      img.shop,
      ["Next.js", "Stripe", "PayPal", "Catalogue"],
      {
        name: "E-commerce",
        summary: "Boutiques en ligne : catalogue, paiement, livraison, et ce qui se passe après l'achat.",
        description: "Vendre en ligne demande plus qu'un thème. Nous structurons le catalogue, le paiement, les frais de livraison et les pages qui rassurent avant le paiement.",
        problem: "Un catalogue incomplet, un paiement qui échoue, ou des frais surprises font abandonner le panier. Le trafic payant amplifie alors la perte.",
        solution: "Nous concevons la boutique autour du parcours d'achat réel : mobile, confiance, Stripe, PayPal ou facturation B2B, et un tableau de bord pour suivre les commandes.",
        benefits: ["Un parcours d'achat court", "Stripe, PayPal et moyens adaptés à votre marché", "Un catalogue administrable", "Des bases pour la publicité produit"],
        process: [
          { title: "Offre", text: "Produits, marges, livraison, et ce qui doit être simple dès le premier jour." },
          { title: "Parcours", text: "Fiche, panier, paiement, confirmation. Chaque friction est une décision." },
          { title: "Construction", text: "Boutique, moyens de paiement, et contenus de réassurance." },
          { title: "Lancement", text: "Premières commandes test, puis acquisition une fois le tunnel stable." },
        ],
        faq: [
          { q: "Quels paiements ?", a: "Selon le projet : Stripe, PayPal, cartes via passerelle, ou facturation B2B si c'est votre modèle." },
          { q: "Shopify ou sur mesure ?", a: "Shopify quand la vitesse de lancement prime. Sur mesure quand le parcours ou le catalogue ne rentrent pas dans un thème." },
        ],
        seoTitle: "Création de site e-commerce",
        seoDescription: "Boutiques en ligne : catalogue, Stripe / PayPal, livraison et acquisition.",
      },
      {
        name: "E-commerce",
        summary: "Online shops: catalogue, payment, delivery, and what happens after the order.",
        description: "Selling online takes more than a theme. We structure the catalogue, payment, delivery fees and the pages that reassure before checkout.",
        problem: "An incomplete catalogue, a failing payment or surprise fees abandon the cart. Paid traffic then amplifies the loss.",
        solution: "We design the shop around the real purchase path: mobile, trust, Stripe, PayPal or B2B invoicing, and a dashboard for orders.",
        benefits: ["A short checkout", "Stripe, PayPal and methods for your market", "A catalogue you can run", "A base for product ads"],
        process: [
          { title: "Offer", text: "Products, margins, delivery, and what must be simple on day one." },
          { title: "Path", text: "Product, cart, payment, confirmation. Each friction is a decision." },
          { title: "Build", text: "Shop, payment methods, and reassurance content." },
          { title: "Launch", text: "Test orders, then acquisition once the tunnel is stable." },
        ],
        faq: [
          { q: "Which payments?", a: "Depending on the project: Stripe, PayPal, card gateways, or B2B invoicing if that is your model." },
          { q: "Shopify or custom?", a: "Shopify when launch speed matters. Custom when the path or catalogue does not fit a theme." },
        ],
        seoTitle: "E-commerce website design",
        seoDescription: "Online shops: catalogue, Stripe / PayPal, delivery and acquisition.",
      },
      {
        name: "التجارة الإلكترونية",
        summary: "متاجر إلكترونية: كتالوج ودفع وتوصيل وما بعد الطلب.",
        description: "البيع عبر الإنترنت أكثر من قالب. نبني الكتالوج والدفع ومصاريف التوصيل وصفحات الثقة قبل الأداء.",
        problem: "كتالوج ناقص أو دفع يفشل أو مصاريف مفاجئة تُسقط السلة. الإعلان المدفوع يضخّم الخسارة.",
        solution: "نصمم المتجر حول مسار الشراء الحقيقي: الهاتف والثقة وStripe وPayPal أو فوترة B2B.",
        benefits: ["مسار شراء قصير", "Stripe وPayPal ووسائل تناسب سوقكم", "كتالوج يمكن تسييره", "أساس لإعلانات المنتجات"],
        process: [
          { title: "العرض", text: "المنتجات والهوامش والتوصيل." },
          { title: "المسار", text: "البطاقة والسلة والدفع والتأكيد." },
          { title: "البناء", text: "المتجر ووسائل الدفع والطمأنة." },
          { title: "الإطلاق", text: "طلبات تجريبية ثم الاكتساب." },
        ],
        faq: [
          { q: "ما وسائل الدفع؟", a: "حسب المشروع: Stripe أو PayPal أو بطاقات عبر بوابة، أو فوترة B2B." },
          { q: "Shopify أم حسب الطلب؟", a: "Shopify حين تهم سرعة الإطلاق. حسب الطلب حين لا يناسب المسار قالبًا." },
        ],
        seoTitle: "إنشاء متجر إلكتروني",
        seoDescription: "متاجر إلكترونية: كتالوج وStripe / PayPal وتوصيل واكتساب.",
      },
    ),
  ];
}

const all = [...services, ...rest()];

export function staticServices(locale: Locale): Service[] {
  return all.map((service) => ({
    slug: service.slug,
    icon: service.icon,
    image: service.image,
    tools: service.tools,
    ...service.copy[locale],
  }));
}

export const serviceSlugs = all.map((service) => service.slug);
